######################################################################
# Automatically generated by qmake (3.0) ?? 4? 13 09:29:03 2014
######################################################################

TEMPLATE = app
TARGET = cacheGui
INCLUDEPATH += .
QT += widgets
# Input
HEADERS += cache.h idcache.h mainwindow.h ui_mainwindow.h unicache.h
FORMS += mainwindow.ui
SOURCES += cache.cc idcache.cc main.cpp mainwindow.cpp unicache.cc
