######################################################################
# Automatically generated by qmake (3.0) ?? 4? 29 10:48:53 2014
######################################################################

TEMPLATE = app
TARGET = tomasulo
INCLUDEPATH += .
QT += widgets

# Input
HEADERS += cdb.h mainwindow.h tomasulo.h virtualregister.h ui_mainwindow.h
FORMS += mainwindow.ui
SOURCES += main.cpp mainwindow.cpp tomasulo.cpp
